### ISSUE TITLE
MHA suddenly missing header analysis information

### ISSUE THREAD

**Issue by jimbotechsys** [microsoft/MHA#956]
For about the last week, MHA show no information at all (_except_ Original Headers) on the Summary tab, only _one_ server on the Received tab, the Antispam tab template is void of _any_ analysis data, Other is completely blank and the Copy function only shows _one_ of the transit (originating?) servers.

I have tried changing the UI style but it made no difference. I have uninstalled the Add-In, rebooted, reinstalled the Add-In and the issue persists.

This is a very small shop on O365 E3 for all users and no changes have been made for at least 2 months.

**Comment by ajf15cc** [comment]
I've also experienced exactly the same behaviour over the past week or so.

**Comment by adamtlittleFF** [comment]
I'm seeing the same behavior across multiple tenants.  In the diagnostic messages all refer to a REST permissions issue.

**Comment by johnrkellgren** [comment]
I'm also not sure what has happened to MHA, but it makes it much more difficult to use. This has been one of my most valuable add-ins for the last couple of years.

**Comment by johnrkellgren** [comment]
I've heavily used MHA for the past couple of years and whatever has happened to this valuable add-in makes interpreting the header usage on these emails very difficult and extremely time-consuming.

**Comment by asheroto** [comment]
I have also experienced this issue. The issue has also been reported on Microsoft's forums:
https://answers.microsoft.com/en-us/outlook_com/forum/all/mha-message-header-analyzer-no-longer-working-on/4b87ceaa-74e8-45c4-b105-bc5669fb6d5a

**Comment by BobThompsonLV** [comment]
We experience the same problem using the installed Outlook for Office 365, New Outlook, and the web client. Does this have anything to do with this change?
https://admin.microsoft.com/AdminPortal/home?ref=MessageCenter/:/messages/MC734315

**Comment by stephenegriffin** [comment]
sorry - bad update - reverted

**Comment by asheroto** [comment]
Awesome, looks like it's fixed now, working on mine.

Thanks @stephenegriffin

**Comment by johnrkellgren** [comment]
Thank you so very much.  Not only is it now very usable, but I like the visual layout better than the previous version--what a time saver. Have a great 2024...

**Comment by BobThompsonLV** [comment]
Mine is working, too. I will follow up with my coworkers.

**Comment by stephenegriffin** [comment]
Fix deployed - sorry about missing this report earlier

**Comment by rawtechnologies** [comment]
This is still not working on Outlook for Mac. I just uninstalled and re-installed MHA and the headers are always blank.

**Comment by rawtechnologies** [comment]
Even the original headers are blank.

**Comment by stephenegriffin** [comment]
@rawtechnologies likely a completely different/new issue. Please go to diagnostics (gear/diagnostics button) and copy out the contents of the diagnostics and paste them into a new issue
